### ISSUE TITLE
Initial Code Review

### ISSUE THREAD

**Issue by kjohnson** [impress-org/give-activecampaign#1]
- **give-activecampaign.php**
	- [x] L374: Missing validation for return of `$tags`
		- PHP Warning breaks donation form submission when WP_DEBUG is enabled. `Warning: Invalid argument supplied for foreach() in .../give-activecampaign/give-activecampaign.php on line 374`
	- [x] L379 Assumes that lists/tags were added successfuly - not sure if verification is important enough here to add.
	- [x] L403 No need to manually require if the class is autoloaded.
	- [x] L406 Should consider caching the ActiveCampaign instance, instead of instantiating a new class for each subscription and tag added during a single request (which uses more memory).
	- [x] L412 The bracket syntax suggests that you could send multiple lists in a single request. The documentation is unclear if this is supported. See https://www.activecampaign.com/api/example.php?call=contact_add
	- [x] 452 It looks like you can pass the tags as a comma-separate list, instead of making individual api requests. Reducing the number of external requests will increase performance. See https://www.activecampaign.com/api/example.php?call=contact_add
	- [x] L446 The ActiveCampaign instance should be shared between the `subscribe_email()` and `tag_email()` methods.
		- I would suggest an `api()` method on the main class, which can return a single instance anywhere the method is called.
	- [x] L490:494 Dynamically setting the value of `$output` should happen in an `if/else` here, as opposed to using a default value. 
- **includes/activation.php**
	- [x] L28 The plugin row action for settings is a broken link. The tab parameter should just be "activecampaign", instead of "give-activecampaign".
- **includes/settings.php**
	- [x] L151 The settings class include should not auto-instantiate itself. See PSR-1: Basic Coding Standard
		- > Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both.
		- Suggestion: Move setting class instantiation to Give_ActiveCampaign::global_settings#L326

**Comment by DevinWalker** [comment]
All suggestions have been made except some more API optimizations but the changes I've made ensure the API for subscribing both lists and tags is only made once versus each time for tags which I believe satisfies the requirements here.
